default: &default
  key_path: /path/to/key.pem
  repo_url: https://github.com/standardnotes/standard-journal.git
  user: ssh_username

staging:
  <<: *default
  server: staging.yourdomain.com
  branch: staging
  deploy_to: ~/standard-notes-staging-server

production:
  <<: *default
  server: yourdomain.com
  deploy_to: ~/standard-notes-prod-server
